### ISSUE TITLE
求时序分析的代码与热图聚类（k-mer）的代码

### ISSUE THREAD

**Issue by hushaoqiang** [xmliu01/Uncovering-the-TRN-involved-in-boosting-wheat-regeneration-and-transformation#2]
您好，请问可以提供一下Pseudotime analysis与热图聚类（k-mer）的代码吗？网上看了很多，很乱。我想按照您的代码来做我的研究，十分感谢。

**Comment by Qiuqoo** [comment]
您好，请问您找到方法了，我也很需要

**Comment by hushaoqiang** [comment]
> 您好，请问您找到方法了，我也很需要

**Comment by hushaoqiang** [comment]
没找到，后面换课题了，就不搞了

**Comment by Qiuqoo** [comment]
热图聚类我做出来了，但是不知道怎么提取每一个簇内的信息，通过ComplexHeatmap&nbsp; 包内的row_ordre函数得到的每个簇内的信息和热图并不对应。时序分析我用Tcseq这个R包做出来了，但是和这篇文章中的形式不太一样《Uncovering the transcriptional regulatory  network involved in boosting wheat  regeneration and transformation》。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xmliu01/Uncovering-the-TRN-involved-in-boosting-wheat-regeneration-and-transformation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月28日(星期三) 晚上6:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xmliu01/Uncovering-the-TRN-involved-in-boosting-wheat-regeneration-and-transformation] 求时序分析的代码与热图聚类（k-mer）的代码 (Issue #2)





 
没找到，后面换课题了，就不搞了

**Comment by hushaoqiang** [comment]
那我就不清楚了，只能找其他方式联系作者。

**Comment by xmliu01** [comment]
https://mp.weixin.qq.com/s/Y203ep6cpR6DyTjoMKgflA

**Comment by hushaoqiang** [comment]
> https://mp.weixin.qq.com/s/Y203ep6cpR6DyTjoMKgflA

好滴，谢谢
